name=SmtpMini
version=1.0.0
author=Davide Lupi <copida.soft@gmail.com>
maintainer=Davide Lupi <copida.soft@gmail.com>
sentence=Minimal secure SMTP client for ESP32 with RAM and filesystem attachments.
paragraph=Lightweight Arduino library for sending secure emails via SMTP with text or HTML body, attachments from RAM or filesystem, and streaming Base64 encoding to minimize memory usage.
category=Communication
url=https://github.com/copida/SmtpMini
architectures=esp32
includes=SmtpMini.h